### ISSUE TITLE
Lots of ttf fonts doesn't load

### ISSUE THREAD

**Issue by soywiz** [korlibs/korim#18]
This one for example:
https://www.dafont.com/es/chunky-wally.font

```
java.lang.ArrayIndexOutOfBoundsException: Index 13366 out of bounds for length 12088
	at com.soywiz.korim.font.ttf.TtfFont$Glyph.contour(TtfFont.kt:444)
	at com.soywiz.korim.font.ttf.TtfFont$Glyph.contour$default(TtfFont.kt:443)
	at com.soywiz.korim.font.ttf.TtfFont$Glyph.createGraphicsPath(TtfFont.kt:475)
	at com.soywiz.korim.font.ttf.TtfFont$Glyph.fill-6R-LPU4(TtfFont.kt:461)
	at com.soywiz.korim.font.ttf.TtfFont.fillText-szaLBVk(TtfFont.kt:397)
	at com.soywiz.korim.font.ttf.TtfFontKt.fillText-BW0PsmY(TtfFont.kt:676)
```

**Comment by soywiz** [comment]
Fixed by #22
